[tool.black]
line-length = 100
preview = true
include = '(ai_diffusion|scripts|tests)/.*\.pyi?$'
extend-exclude = 'websockets|krita\.pyi$'

[tool.pyright]
include = ["ot_plugin", "scripts/*.py", "tests"]
exclude = [
    "**/__pycache__",
    "**/.pytest_cache",
    "**/.server",
    "tests/server",
    "tests/test_image_transfer.py",
    "ot_plugin/websockets",
]
ignore = ["ot_plugin/websockets", "krita.pyi"]
extraPaths = ["scripts/typeshed"]
reportMissingModuleSource = false

[tool.pytest.ini_options]
testpaths = ["tests"]
